version: "3.8"

services:
  postgresDB:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/var/lib/postgres/data
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  back:
    image: ticketappwns/ticketapp_back
    ports:
      - "4001:4000"
    depends_on:
      - postgresDB
    command: sh -c "yarn seed:prod && yarn start"

  front:
    image: ticketappwns/ticketapp_front
    ports:
      - "3001:3000"
    volumes:
      - ./front/src:/front/src
    depends_on:
      - back
    command: sh -c "dockerize -wait tcp://back:4000 -timeout 300s -wait-retry-interval 5s  yarn dev"
