version: "3.8"

services:
  postgresDB:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/var/lib/postgres/data
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  back:
    image: ticketappwns/ticketapp_back
    ports:
      - "4000:4000"
    depends_on:
      - postgresDB
    command: sh -c "yarn seed:prod && yarn build && yarn prod"

  front:
    image: ticketappwns/ticketapp_front
    volumes:
      - web-front-build:/front/dist
    command: sh -c "yarn build"

  nginx:
    image: nginx:1.21.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-front-build:/web-front-build
      - ./logs:/var/log/nginx
    ports:
      - ${GATEWAY_PORT:-3000}:80
    depends_on:
      - front
      - back
    restart: always

volumes:
  web-front-build:
