version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./files_services/src:/files_services/src
  filesservice:
    image: files_services
    ports:
      - 3020:8080