FROM node:lts-alpine

ARG NODE_ENV=prod
ENV NODE_ENV=${NODE_ENV}

WORKDIR /back

COPY package.json ./
COPY yarn.lock ./

RUN yarn global add ts-node
RUN yarn

COPY tsconfig.json ./
COPY ormconfig.js ./
COPY jest.config.js ./
COPY .env.test ./
COPY .env.prod ./

COPY src src

CMD yarn dev
