FROM node:lts-alpine AS builder
WORKDIR /back

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./

RUN yarn

COPY src src

RUN yarn build

FROM node:lts-alpine
WORKDIR /back
COPY --from=builder /back/build /back/build

ARG NODE_ENV=prod
ENV NODE_ENV=${NODE_ENV}
ENV DB_NAME=${NODE_ENV}

COPY package.json ./
COPY yarn.lock ./
COPY ormconfig.js ./
RUN yarn install --production
RUN yarn seed:prod

CMD yarn start
