FROM node:lts-alpine 

RUN mkdir /back
WORKDIR /back

COPY .env.test ./
COPY .env.prod ./
COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./
COPY ormconfig.json ./

RUN yarn

COPY src src

COPY .env.test ./src
COPY .env.prod ./src

CMD yarn dev
